version: '2'
services:
  cassandra-1:
    image: cassandra
    container_name: cassandra-1
    ports:
    - 9042
    environment:
      CASSANDRA_BROADCAST_ADDRESS: "cassandra-1"
    volumes:
    - "cassandra1:/var/lib/cassandra"
    restart: always

  cassandra-migration:
    depends_on:
      - cassandra-1
    extends:
      file: cassandra-migration.yml
      service: cassandra-migration
    links:
      - cassandra-1
    environment:
      - CREATE_KEYSPACE_SCRIPT=create_keyspace_datafabrcis.cql
      - CASSANDRA_CONTACT_POINT=cassandra-1

volumes:
  cassandra1:

networks:
  datafabrics-overlay:
    driver: overlay